// Mapping for uploaded Teacher Mode snippets. Extend as you upload more.
// We keep separate maps for lowercase and uppercase graphemes.

export const LOWERCASE_SNIPPETS = {
  'a': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/2xgjbtvs_Lowercase%20a.m4a',
  'b': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/ke1i392q_Lowercase%20b.m4a',
  'c': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/ix0zn02s_Lowercase%20c.m4a',
  'cs': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/fw2a0m0s_Lowercase%20cs.m4a',
  'd': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/tw73jco1_Lowercase%20d.m4a',
  'dz': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/rn4rgh55_Lowercase%20dz.m4a',
  'dzs': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/y46rl1uh_Lowercase%20dzs.m4a',
  'e': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/jeazml3q_Lowercase%20e.m4a',
  'é': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/za3ec8ad_Lowercase%20e%CC%81.m4a',
  'f': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/9t8tkpdi_Lowercase%20f.m4a',
  'g': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/nmwdvjev_Lowercase%20g.m4a',
  'gy': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/1wxsusox_Lowercase%20gy.m4a',
  'h': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/0qnhzlbr_Lowercase%20h.m4a',
  'i': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/hkvoqmbz_Lowercase%20i.m4a',
  'í': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/f620pl5g_Lowercase%20i%CC%81.m4a',
  'j': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/arqchhld_Lowercase%20j.m4a',
  'k': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/8e48de20_Lowercase%20k.m4a',
  'l': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/9r9rbiqd_Lowercase%20l.m4a',
  'ly': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/8xsmc0s9_Lowercase%20ly.m4a',
  'm': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/xd8qlbpc_Lowercase%20m.m4a',
  'n': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/a7u1x84y_Lowercase%20n.m4a',
  'ny': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/299r9hyx_Lowercase%20ny.m4a',
  'o': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/fnoql90x_Lowercase%20o.m4a',
  'ó': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/p4go76o7_Lowercase%20o%CC%81.m4a',
  'ö': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/74o1bedn_Lowercase%20o%CC%88.m4a',
  'ő': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/7ou878n9_Lowercase%20o%CC%8B.m4a',
  'p': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/th8l22av_Lowercase%20p.m4a',
  'q': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/6cgocmui_Lowercase%20q.m4a',
  'r': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/k3w8t1uj_Lowercase%20r.m4a',
  's': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/usgj58eu_Lowercase%20s.m4a',
  'sz': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/kalxjud4_Lowercase%20sz.m4a',
  't': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/7jguj3sk_Lowercase%20t.m4a',
  'ty': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/q75ev9ke_Lowercase%20ty.m4a',
  'u': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/e43lys35_Lowercase%20u.m4a',
  'ú': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/agtpg422_Lowercase%20u%CC%81.m4a',
  'ü': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/cb2ugmju_Lowercase%20u%CC%88.m4a',
  'ű': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/d60qwkf4_Lowercase%20u%CC%8B.m4a',
  'v': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/e3gt2yyb_Lowercase%20v.m4a',
  'w': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/5n8lt7gd_Lowercase%20w.m4a',
  'x': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/i9myzpkl_Lowercase%20x.m4a',
  'y': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/ro691oi0_Lowercase%20y.m4a',
  'z': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/tfve9ezr_Lowercase%20z.m4a',
  'zs': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/97wd3zbu_Lowercase%20zs.m4a',
};

export const UPPERCASE_SNIPPETS = {
  'A': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/99ehm7eg_Uppercase%20A.m4a',
  'Á': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/a0oh5tyk_Uppercase%20A%CC%81.m4a',
  'B': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/2jd3ok1h_Uppercase%20B.m4a',
  'C': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/dj6egds8_Uppercase%20C.m4a',
  'CS': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/kef92c3q_Uppercase%20Cs.m4a',
  'D': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/shmghbye_Uppercase%20D.m4a',
  'DZ': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/t5636i0t_Uppercase%20DZ.m4a',
  'DZS': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/zg5u2pqj_Uppercase%20DZS.m4a',
  'E': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/8me9pn2p_Uppercase%20E.m4a',
  'É': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/l87a3lq6_Uppercase%20E%CC%81.m4a',
  'F': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/d0hvkjox_Uppercase%20F.m4a',
  'G': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/ecfo8vj9_Uppercase%20G.m4a',
  'GY': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/h26ej2ek_Uppercase%20Gy.m4a',
  'H': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/ausfjngb_Uppercase%20H.m4a',
  'I': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/b6714ls2_Uppercase%20I.m4a',
  'Í': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/m2v6zknf_Uppercase%20I%CC%81.m4a',
  'J': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/fxfs1hkp_Uppercase%20J.m4a',
  'K': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/ub4ognwe_Uppercase%20K.m4a',
  'L': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/st39fznu_Uppercase%20L.m4a',
  'LY': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/qle3it91_Uppercase%20Ly.m4a',
  'M': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/1i9mt415_Uppercase%20M.m4a',
  'N': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/14rlfjoe_Uppercase%20N.m4a',
  'NY': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/a3y5gege_Uppercase%20Ny.m4a',
  'O': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/j35mpsx7_Uppercase%20O.m4a',
  'Ó': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/5poaubx5_Uppercase%20O%CC%81.m4a',
  'Ö': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/c9zjokg5_Uppercase%20O%CC%88.m4a',
  'Ő': 'https://customer-assets.emergentagent.com/job_magyar-abc/artifacts/zp39tdd1_Uppercase%20O%CC%8B.m4a',
};

export default { LOWERCASE_SNIPPETS, UPPERCASE_SNIPPETS };